#production
deployment:
  user: root
  from: ./
  to: ~/vhosts/mement.nl/
  excludes:
releases:
  enabled: true
  max: 2
  symlink: htdocs
  directory: releases
hosts:
  - 83.137.145.57
tasks:
  pre-deploy:
  on-deploy:
  post-release:
  post-deploy:
