<?php

namespace AppBundle\Repository;

/**
 * TriangleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TriangleRepository extends \Doctrine\ORM\EntityRepository
{
}
